---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/oauth.yaml
  - resources/vault-ldap-secret.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: ldap-ca
  namespace: openshift-config
  files:
  - ca.crt=data/ldap-ca.pem