---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: health-check-placement
  namespace: policies-dev
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: env
          operator: In
          values:
          - dev
