---
default:
  app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    enabled: true
    enableAutoSync: true
    autoSyncPrune: true
    project: cluster-config
    destination:
      namespace: platform-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/Oscarlind/cluster-configs
      targetRevision: main

projects:
  cluster-config:
    annotations:
      argocd.argoproj.io/sync-wave: "-2"
    description: Project for ACM policies
    namespace: platform-gitops
    sourceRepos:
      - https://github.com/Oscarlind/cluster-configs
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:


######################################
#        ACM POLICIES - DEV          #
######################################

  # baseline:
  #   annotations:
  #     argocd.argoproj.io/sync-wave: "20"
  #   source:
  #     path: example-3/overlays/policies/dev/baseline

  health-checks:
    annotations:
      argocd.argoproj.io/sync-wave: "25"
    source:
      path: example-3/overlays/policies/dev/health-checks


######################################
#        ACM POLICIES - QA           #
######################################

######################################
#        ACM POLICIES - PROD         #
######################################
