---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-example-1
  namespace: platform-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/oscarlind/cluster-configs
    targetRevision: main
    path: example-1/overlays/dev/pacman
  destination:
    server: https://kubernetes.default.svc