---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/sealed-secrets/

# Remove the SCC requiring anyuid
patches:
- path: patch-sealed-secrets.yaml
  target:
    group: apps
    kind: Deployment
    name: sealed-secrets-controller
    version: v1
# Ensure that key-renewal is turned off
- path: patch-key-renewal.yaml
  target:
    group: apps
    kind: Deployment
    name: sealed-secrets-controller
    version: v1
