---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: pacman
    namespace: platform-gitops
spec:
    project: default
    source:
        repoURL: https://github.com/oscarlind/cluster-configs
        targetRevision: main
        path: example-2/charts/pacman
    helm:
      valueFiles:
      - values-dev.yaml
    destination:
        server: https://kubernetes.default.svc
