---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-ldap-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-common
    kind: ClusterSecretStore
  target:
    name: ldap-secret
  data:
    - secretKey: bindPassword
      remoteRef:
        key: ldap-secret
        property: bindPassword