---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/proxy.yaml

generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
- name: custom-ca
  namespace: openshift-config
  files:
  - ca-bundle.crt=data/ca-bundle.pem
