{{- if .Values.pacman.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pacman
  name: pacman
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.pacman.replicas }}
  selector:
    matchLabels:
      name: pacman
  template:
    metadata:
      labels:
        name: pacman
    spec:
      containers:
      - image: quay.io/jpacker/nodejs-pacman-app:latest
        name: pacman
        ports:
        - containerPort: 8080
          name: http-server
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pacman
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: pacman
spec:
  path: "/"
  to:
    kind: Service
    name: pacman
---
apiVersion: v1
kind: Service
metadata:
  name: pacman
  namespace: {{ .Values.namespace }}
  labels:
    name: pacman
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: pacman
{{- end }}