---
default:
  app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    enabled: true
    enableAutoSync: true
    autoSyncPrune: true
    project: cluster-config
    destination:
      namespace: platform-gitops
      server: https://kubernetes.default.svc
    source:
      repoURL: git@github.com:Oscarlind/cluster-configs.git
      targetRevision: main

projects:
  cluster-config:
    annotations:
      argocd.argoproj.io/sync-wave: "-2"
    description: Project for overall cluster configuration
    namespace: platform-gitops
    sourceRepos:
      - git@github.com:Oscarlind/cluster-configs.git
    destinations: |
      - namespace: '*'
        server: https://kubernetes.default.svc
    extraFields: |
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'

applications:

  pacman:
    annotations:
      argocd.argoproj.io/sync-wave: "10"
    source:
      path: clusters/dev/pacman

  cluster-proxy:
    annotations:
      argocd.argoproj.io/sync-wave: "11"
      argocd.argoproj.io/sync-options: ServerSideApply=true
    source:
      path: clusters/dev/cluster-proxy

  external-secrets:
    annotations:
      argocd.argoproj.io/sync-wave: "12"
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    source:
      path: clusters/dev/external-secrets

  oauth:
    annotations:
      argocd.argoproj.io/sync-wave: "13"
    source:
      path: clusters/dev/oauth

  ldap-group-sync:
    annotations:
      argocd.argoproj.io/sync-wave: "14"
      argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    source:
      path: clusters/dev/ldap-group-sync

